export const roles = {
    ADMIN: 'admin',
    MANAGEMENT: 'management',
    EMPLOYEE: 'employee',
} as const

export const defaultAvatar =
    'https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211467.png'

export const users: User[] = [
    {
        _id: 'usr_001',
        idNo: '1001',
        fullName: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: false,
        status: true,
        img: 'https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211467.png',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'Software Engineer',
        department: 'dept_001',
        dateOfBirth: '1992-07-15',
        joiningDate: '2021-05-10',
        phone: '+1-555-123-4567',
        emergencyContact: '+1-555-765-4321',
        secondaryEmail: 'alice.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:30:00Z',
        updatedAt: '2025-09-25T10:30:00Z',
        isPasswordChanged: true,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_002',
        idNo: '1002',
        fullName: 'Brian Smith',
        email: 'brian.smith@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.MANAGEMENT,
        initialLogin: false,
        status: true,
        img: 'https://wac-cdn.atlassian.com/dam/jcr:ba03a215-2f45-40f5-8540-b2015223c918/Max-R_Headshot%20(1).jpg?cdnVersion=2990',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'Product Manager',
        department: 'dept_002',
        dateOfBirth: '1988-03-22',
        joiningDate: '2020-09-14',
        phone: '+1-555-234-5678',
        emergencyContact: '+1-555-876-5432',
        secondaryEmail: 'brian.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:31:00Z',
        updatedAt: '2025-09-25T10:31:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_003',
        idNo: '1003',
        fullName: 'Catherine Lee',
        email: 'catherine.lee@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: true,
        status: true,
        img: 'https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211467.png',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'UI/UX Designer',
        department: 'dept_003',
        dateOfBirth: '1995-11-09',
        joiningDate: '2022-01-20',
        phone: '+1-555-345-6789',
        emergencyContact: '+1-555-987-6543',
        secondaryEmail: 'catherine.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:32:00Z',
        updatedAt: '2025-09-25T10:32:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_004',
        idNo: '1004',
        fullName: 'David Brown',
        email: 'david.brown@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.ADMIN,
        initialLogin: false,
        status: true,
        img: 'https://wac-cdn.atlassian.com/dam/jcr:ba03a215-2f45-40f5-8540-b2015223c918/Max-R_Headshot%20(1).jpg?cdnVersion=2990',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'HR Manager',
        department: 'dept_004',
        dateOfBirth: '1985-06-12',
        joiningDate: '2019-03-05',
        phone: '+1-555-456-7890',
        emergencyContact: '+1-555-654-3210',
        secondaryEmail: 'david.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:33:00Z',
        updatedAt: '2025-09-25T10:33:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_005',
        idNo: '1005',
        fullName: 'Emily Davis',
        email: 'emily.davis@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: true,
        status: true,
        img: 'https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211467.png',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'QA Engineer',
        department: 'dept_001',
        dateOfBirth: '1993-01-18',
        joiningDate: '2023-07-01',
        phone: '+1-555-567-8901',
        emergencyContact: '+1-555-210-9876',
        secondaryEmail: 'emily.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:34:00Z',
        updatedAt: '2025-09-25T10:34:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_006',
        idNo: '1006',
        fullName: 'Frank Wilson',
        email: 'frank.wilson@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: false,
        status: true,
        img: 'https://wac-cdn.atlassian.com/dam/jcr:ba03a215-2f45-40f5-8540-b2015223c918/Max-R_Headshot%20(1).jpg?cdnVersion=2990',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'DevOps Engineer',
        department: 'dept_002',
        dateOfBirth: '1990-09-27',
        joiningDate: '2021-08-15',
        phone: '+1-555-678-9012',
        emergencyContact: '+1-555-321-0987',
        secondaryEmail: 'frank.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:35:00Z',
        updatedAt: '2025-09-25T10:35:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_007',
        idNo: '1007',
        fullName: 'Grace Miller',
        email: 'grace.miller@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: false,
        status: true,
        img: 'https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211467.png',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'Business Analyst',
        department: 'dept_003',
        dateOfBirth: '1994-12-02',
        joiningDate: '2020-10-21',
        phone: '+1-555-789-0123',
        emergencyContact: '+1-555-432-1098',
        secondaryEmail: 'grace.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:36:00Z',
        updatedAt: '2025-09-25T10:36:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_008',
        idNo: '1008',
        fullName: 'Henry Clark',
        email: 'henry.clark@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: true,
        status: true,
        img: 'https://wac-cdn.atlassian.com/dam/jcr:ba03a215-2f45-40f5-8540-b2015223c918/Max-R_Headshot%20(1).jpg?cdnVersion=2990',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'Frontend Developer',
        department: 'dept_001',
        dateOfBirth: '1991-04-30',
        joiningDate: '2022-04-10',
        phone: '+1-555-890-1234',
        emergencyContact: '+1-555-543-2109',
        secondaryEmail: 'henry.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:37:00Z',
        updatedAt: '2025-09-25T10:37:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_009',
        idNo: '1009',
        fullName: 'Isabella Moore',
        email: 'isabella.moore@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: false,
        status: true,
        img: 'https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211467.png',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'Backend Developer',
        department: 'dept_002',
        dateOfBirth: '1996-08-25',
        joiningDate: '2023-02-12',
        phone: '+1-555-901-2345',
        emergencyContact: '+1-555-654-0987',
        secondaryEmail: 'isabella.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:38:00Z',
        updatedAt: '2025-09-25T10:38:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
    {
        _id: 'usr_010',
        idNo: '1010',
        fullName: 'Jack Taylor',
        email: 'jack.taylor@example.com',
        password: '$2b$10$abcdefghijklmnopqrstuv',
        role: roles.EMPLOYEE,
        initialLogin: false,
        status: true,
        img: 'https://wac-cdn.atlassian.com/dam/jcr:ba03a215-2f45-40f5-8540-b2015223c918/Max-R_Headshot%20(1).jpg?cdnVersion=2990',
        clock_in: '10.25',
        clock_out: '7.12',
        break_time: '1.23',
        total_working_hour: '8.23',
        designation: 'Support Engineer',
        department: 'dept_004',
        dateOfBirth: '1989-10-08',
        joiningDate: '2018-11-30',
        phone: '+1-555-012-3456',
        emergencyContact: '+1-555-765-4320',
        secondaryEmail: 'jack.backup@example.com',
        attendanceFace: true,
        attendanceManual: false,
        createdAt: '2025-09-25T10:39:00Z',
        updatedAt: '2025-09-25T10:39:00Z',
        isPasswordChanged: false,
        shifts: [
            { day: 'saturday', start_time: '', end_time: '', day_off: true },
            { day: 'sunday', start_time: '', end_time: '', day_off: true },
            { day: 'monday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'tuesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'wednesday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'thursday', start_time: '10:00', end_time: '19:00', day_off: false },
            { day: 'friday', start_time: '10:00', end_time: '19:00', day_off: false },
        ],
        attendance: {
            faceRecognition: true,
            manual: true,
        },
        muteNotifications: false,
    },
]
